AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength: 
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

  Max: 25
  AllowedMethods: ['describe', 'context', 'feature']